version: '3.8'

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:80"
    restart: unless-stopped
  
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - MOYSKLAD_API_TOKEN=eba6f80476e5a056ef25f953a117d660be5d568