version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ~/.postgresql:/root/.postgresql:ro
      - ./backend/app/credentials:/app/credentials:ro
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - analyzer-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - analyzer-network

networks:
  analyzer-network:
    driver: bridge