version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: louella
      POSTGRES_PASSWORD: XBcMJoEO1ljb
      POSTGRES_DB: MS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    volumes:
      - ~/.postgresql:/root/.postgresql:ro
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_WORKERS=2
      - UVICORN_TIMEOUT=300
      - DB_HOST=db  # Используем имя сервиса
      - DB_PORT=5432
      - DB_NAME=MS
      - DB_USER=louella
      - DB_PASSWORD=XBcMJoEO1ljb
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data: