FROM python:3.9-slim

WORKDIR /app

# Сначала копируем только requirements.txt для кэширования
COPY ./backend/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Затем копируем остальные файлы
COPY ./backend /app

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]