version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Пробрасываем порт 80 контейнера на порт 80 хоста
    restart: unless-stopped  # Автоматически перезапускать контейнер при падении

