FROM python:3.9-slim

WORKDIR /app

# Копируем requirements.txt первым для кэширования
COPY ./backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Затем копируем остальные файлы
COPY ./backend .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--timeout", "120", "app:app"]