version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: analyzer-backend
    volumes:
      - ~/.postgresql:/root/.postgresql:ro
      - ./backend/app/credentials:/app/credentials:ro
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - analyzer-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyzer-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - analyzer-net

networks:
  analyzer-net:
    driver: bridge